### ISSUE TITLE
Dataset copy goes through table schema check

### ISSUE THREAD

**Issue by B0yc3y** [polleyg/gcp-dataflow-copy-bigquery#6]
Table spec is applied to data sets. Apache beam BigQueryIO package doesn't expose the dataset regex they have. 

Probably best to copy the regex for now, and I'll raise a PR over there to expose a method to ensure the dataset matches the dataset schema.

Culprit block in config
```
copies:
# Dataset copy
- source: bigquery-public-data:world_bank_wdi
  target: TEST_PROJECT:world_bank_wdi
  numWorkers: 2
  maxNumWorkers: 2
```

Error:
```
> Task :run
15:30:11,854 0    [main] INFO  org.polleyg.BQTableCopyPipeline - BigQuery table copy: Config{copies=[{source=bigquery-public-data:world_bank_wdi, target=TEST_PROJECT:world_bank_wdi, numWorkers=2, maxNumWorkers=2}, {source=bigquery-public-data:world_bank_wdi.country_series_definitions, target=TEST_PROJECT:world_bank_wdi_US.country_series_definitions, maxNumWorkers=1, workerMachineType=n1-standard-2, writeDisposition=append, targetDatasetLocation=US}, {source=bigquery-public-data:world_bank_wdi.country_series_definitions, target=TEST_PROJECT:world_bank_wdi_EU.country_series_definitions, maxNumWorkers=1, workerMachineType=n1-standard-2, writeDisposition=append, targetDatasetLocation=EU}], project='TEST_PROJECT', runner='dataflow', workerMachineType='n1-standard-1', numWorkers='1', maxNumWorkers='3', targetDatasetLocation='null', zone='australia-southeast1-a', writeDisposition='truncate', detectSchema='true'}
Exception in thread "main" java.lang.IllegalArgumentException: Table reference is not in [project_id]:[dataset_id].[table_id] format: bigquery-public-data:world_bank_wdi
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryHelpers.parseTableSpec(BigQueryHelpers.java:384)
	at org.polleyg.GCPHelpers.isDatasetTableSpec(GCPHelpers.java:201)
	at org.polleyg.BQTableCopyPipeline.copy(BQTableCopyPipeline.java:86)
	at org.polleyg.BQTableCopyPipeline.main(BQTableCopyPipeline.java:55)
```

**Comment by B0yc3y** [comment]
Looks like it actually creates the dataset from the tablename if it doesnt exist in the function `createBQDataset`, I think the only fix needed is to update the example `config.yaml` to not explicitly list the dataset under the copies key.

**Comment by n0012** [comment]
I had a similar challenge getting the dataset level copy (all tables) to work.  Here's some SQL I wrote to generate YAML for each table.

`
select CONCAT('- source: ', table_catalog, ':', table_schema,'.',table_name
            ,'\n','  target: <TARGET_PROJECT>:', table_schema,'.',table_name
            ,'\n','  numWorkers: 2'
            ,'\n','  maxNumWorkers: 2'
            )
FROM <SOURCE_SCHEMA>.INFORMATION_SCHEMA.TABLES
`
